### ISSUE TITLE
How to train?

### ISSUE THREAD

**Issue by shazib-summar** [subeeshvasu/2018_subeesh_epsr_eccvw#4] opened 2020-07-07 05:38 UTC
Could you please provide a step by step workflow to train this model from scratch? That would be awesome.

This is some pretty cool work btw.

**Comment by subeeshvasu** [comment] 2020-07-07 11:43
Duplicate of #3

**Closed as completed** 2020-07-07 11:43 UTC

**Comment by killerzula** [comment] 2020-07-07 11:51
What about #5?
